# List of parser configurations
parsers:
  # CXXParser should always put first
  - name: CXXParser
    package: '@agoraio-extensions/cxx-parser'
    args:
      includeHeaderDirs:
        - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.4.0/include'
      parseFiles:
        include:
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.4.0/include/*.h'
        exclude:
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.4.0/include/time_utils.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.4.0/include/rte_*.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.4.0/include/IAgoraMediaComponentFactory.h'


# List of renderer configurations
renderers:
#   # Configuration for the first renderer
  - path: ../renders/blueprint-renderer.ts