# get json data
parsers:
  # CXXParser should always put first
  - name: CXXParser
    package: '@agoraio-extensions/cxx-parser'
    args:
      includeHeaderDirs:
        - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.3.0/include'
      parseFiles:
        include:
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.3.0/include/*.h'
        exclude:
          - ''

## from config folder
## from json to code
renderers:
  - path: ../renderer/binding.ts
  - path: ../renderer/binding_test.ts
  - path: ../renderer/api-type.ts